SELECT
    collection_id,
    scientific_name,
    cat_num,
    identification_remarks,
    ACCESSION,
    higher_geog,
    SPEC_LOCALITY,
    flat.VERBATIM_LOCALITY,
    flat.COLLECTING_METHOD,
    flat.COLLECTING_SOURCE,
    VERBATIM_DATE,
    BEGAN_DATE,
    COLLECTORS, 
    SEX,
    AGE_CLASS,
    ATTRIBUTES,
    PREPARATORS,
    PARTS,
    REMARKS,
    MINIMUM_ELEVATION,
    MAXIMUM_ELEVATION,
    ORIG_ELEV_UNITS,
    round(dec_lat,5) dec_lat,
    round(dec_long,5) dec_long,
    COORDINATEUNCERTAINTYINMETERS,
    DATUM,
    ConcatAttributevalue(flat.collection_object_id,'verbatim preservation date') as verbatim_preservation_date,
    ConcatAttributevalue(flat.collection_object_id,'age') as age,
    ConcatAttributevalue(flat.collection_object_id,'unformatted measurements') as unformatted_measurements,
    ConcatAttributevalue(flat.collection_object_id,'reproductive data') as reproductive_data,
    ConcatAttributevalue(flat.collection_object_id,'molt condition') as molt_condition,
    ConcatAttributevalue(flat.collection_object_id,'total length') as total_length,
    ConcatAttributevalue(flat.collection_object_id,'wing chord') as wing_chord,
    ConcatAttributevalue(flat.collection_object_id,'weight') as weight,
    ConcatAttributevalue(flat.collection_object_id,'fat deposition') as fat_deposition,
    ConcatAttributevalue(flat.collection_object_id,'stomach contents') as stomach_contents,
    ConcatAttributevalue(flat.collection_object_id,'extension') as extension,
    ConcatAttributevalue(flat.collection_object_id,'skull ossification') as skull_ossification,
    ConcatAttributevalue(flat.collection_object_id,'gonad') as gonad,
    concatsingleotherid(flat.collection_object_id,'collector number') as collector_number,
    concatsingleotherid(flat.collection_object_id,'original identifier') as original_identifier,
    concatsingleotherid(flat.collection_object_id,'secondary identifier') as secondary_identifier,
    concatsingleotherid(flat.collection_object_id,'DZTB: Denver Zoology Tissue Bird') as DZTB,
    concatsingleotherid(flat.collection_object_id,'collector number') as collector_number,
    habitat
FROM
    flat
WHERE  flat.collection_object_id IN (#collection_object_id#)
ORDER BY cat_num
