SELECT
    scientific_name,
    cat_num,
    ACCESSION,
    higher_geog,
    SPEC_LOCALITY,
    flat.VERBATIM_LOCALITY,
    flat.COLLECTING_METHOD,
    flat.COLLECTING_SOURCE,
    flat.BEGAN_DATE,
    flat.ENDED_DATE,
    flat.VERBATIM_DATE,
    round(dec_lat,5) dec_lat,
    round(dec_long,5) dec_long,
    COLLECTORS,
    decode(trim(flat.sex),
    'male','M',
    'female','F',
    '') sex,
    ATTRIBUTES,
    PREPARATORS,
    PARTS,
    REMARKS,
    flat.MINIMUM_ELEVATION,
    flat.ORIG_ELEV_UNITS,
    flat.DATUM,
    ConcatAttributevalue(flat.collection_object_id,'verbatim preservation date') as verbatim_preservation_date,
    ConcatAttributevalue(flat.collection_object_id,'age') as age,
    ConcatAttributevalue(flat.collection_object_id,'unformatted measurements') as unformatted_measurements,
    ConcatAttributevalue(flat.collection_object_id,'reproductive data') as reproductive_data,
    ConcatAttributevalue(flat.collection_object_id,'molt condition') as molt_condition,
    ConcatAttributevalue(flat.collection_object_id,'total length') as total_length,
    ConcatAttributevalue(flat.collection_object_id,'wing chord') as wing_chord,
    ConcatAttributevalue(flat.collection_object_id,'weight') as weight,
    ConcatAttributevalue(flat.collection_object_id,'fat deposition') as fat_deposition,
    ConcatAttributevalue(flat.collection_object_id,'stomach contents') as stomach_contents,
    ConcatAttributevalue(flat.collection_object_id,'extension') as extension,
    ConcatAttributevalue(flat.collection_object_id,'skull ossification') as skull_ossification,
    ConcatAttributevalue(flat.collection_object_id,'gonad') as gonad,
    concatsingleotherid(flat.collection_object_id,'preparator number') as preparator_number,
    concatsingleotherid(flat.collection_object_id,'original identifier') as original_identifier,
    concatsingleotherid(flat.collection_object_id,'secondary identifier') as secondary_identifier,
    concatsingleotherid(flat.collection_object_id,'DZTB: Denver Zoology Tissue Bird') as DZTB,
    concatsingleotherid(flat.collection_object_id,'collector number') as collector_number,
    concatsingleotherid(flat.collection_object_id,'RMRP: Rocky Mountain Raptor Program') as RMRP,
    concatsingleotherid(flat.collection_object_id,'GWRC: Greenwood Wildlife Rehabilitation Center') as GWRC,
    habitat,
    DECODE(collection_id,'124','BOT-','130','ENTO-','126','FISH-','131','MALA-','113','MAM-','114','ORN-','115','OOL-','144','TEACH-') || cat_num formatted_cat_num,
    NVL(SUBSTR(identification_remarks, 0, INSTR(identification_remarks, '.')-1),identification_remarks) common_name
FROM
    flat
WHERE
    flat.collection_object_id IN (#collection_object_id#)
ORDER BY
    cat_num
